# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'debug'
  outputDirectory: '$(build.binariesDirectory)\$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    jdkOption: 'JDKVersion'
    
- task: VSBuild@1
  inputs:
    solution: '**\UIAndroidTest.csproj'
    platform: 'x64'
    configuration: 'debug'

- task: AppCenterTest@1
  inputs:
    appFile: '$(outputDirectory)'
    artifactsDirectory: '$(Build.ArtifactStagingDirectory)/AppCenterTest'
    frameworkOption: 'uitest'
    uiTestBuildDirectory: '$(build.sourcesdirectory)/UIAndroidTest/bin/debug'
    uiTestToolsDirectory: '$(build.sourcesdirectory)/packages/Xamarin.UITest.*/tools'
    credentialsOption: 'serviceEndpoint'
    serverEndpoint: 'Visual Studio App Center'
    appSlug: 'kelso.sharp-labscloudacademy.onmicrosoft.com/Test-App'
    devices: 'eee5de63'
    localeOption: 'en_US'
